### PR TITLE
Remove Nightly for Bond

### PR DESCRIPTION
**Pull request by sharath-cliqz**

### CODE REVIEW

**Comment by spacifici** [comment]
Do we still need this PR? @sharath-cliqz

**Comment by sharath-cliqz** [comment]
@spacifici Yes. This removes the building of Bond for the nightly.

**Comment by ravjit-cliqz** [comment]
Conflicts @sharath-cliqz

**Comment by sharath-cliqz** [comment]
@ravjit-cliqz Fixed the conflicts.

**Pull request merged**
